### ISSUE TITLE
Internal refs cannot begin with &lt; but external ones can

### ISSUE THREAD

**Issue by nigelmegitt** [speced/respec#4806]
## Description of problem

If a term definition begins with `&lt;` then Respec generates an error 

Example:

```html
<p>Some random <dfn><code>&lt;ltterm</code></dfn>. Ref the <a><code>&lt;ltterm</code></a>.</p>
```

generates an error:
>ReSpec doesn't support expanding this kind of reference.

and in the "Terms defined by this specification" section, a term called `#dfn-ltterm` is generated, which does correctly link back to the definition.

However, an external reference like:

```
<dfn data-cite="TTML2#profile-vocabulary-extension"><code>&lt;ttp:extension&gt;</code></dfn>
```

gets correctly expanded in the "Terms defined by reference" section to:

>[[TTML2](http://localhost:52330/index.html#bib-ttml2)] defines the following:
>
>   * &lt;ttp:extension&gt;

**What happened:**

Instead of listing the defined term an error message was generated, and unexpected text appeared where the defined term should be in the "Terms defined by this specification" section.

**Expected behavior:**

The defined term should appear, with the `&lt;` at the beginning, and no error should be generated.

**It is the same without the &lt;code&gt; element**

Just in case, I tried removing the `<code>` element around the term, and the behaviour was exactly the same.

**Comment by nigelmegitt** [comment]
Example spec processing failure at https://github.com/w3c/dapt/actions/runs/11023589971/job/30615154823?pr=241 includes in the log:

```
  Error: ROR] ReSpec doesn't support expanding this kind of reference.
         Count: 1
        Plugin: core/anchor-expander
      [INFO] [Timeout: 17098ms] Done.
      [FATAL] Error: Errors found during processing.
          at run (file:///home/runner/work/_actions/w3c/spec-prod/v2/node_modules/.pnpm/respec@35.1.2_typescript@5.4.5/node_modules/respec/tools/respec2html.js:268:11)
          at async file:///home/runner/work/_actions/w3c/spec-prod/v2/node_modules/.pnpm/respec@35.1.2_typescript@5.4.5/node_modules/respec/tools/respec2html.js:215:5
    Command `respec -s "http://localhost:3000/index.html?gitRevision=362102d68d401b3285b916bc6c1ec2f55738aba6" -o "index.html.built.html" --verbose -t 20 -e` failed with exit code: 1.
```
