### ISSUE TITLE
parsing with format:markdown fails

### ISSUE THREAD

**Issue by chaals** [speced/respec#4813]
## Description of problem

Taking the example HTML document at the start of the documentation, and adding 

`format: "markdown",`

as the first line of the respecConfig definition I expected it to call the markdown parser and parse markdown added to the content.

Instead, the console produces the following error:

> TypeError: Cannot read properties of undefined (reading 'search')
    at Sr.parseInfoString (markdown.js:60:35)
    at Sr.code (markdown.js:24:48)
    at cn.parse (marked.esm.js:1843:42)
    at parse (marked.esm.js:1803:23)
    at Object.parse (marked.esm.js:2335:28)
    at Function.dn [as parse] (marked.esm.js:2368:27)
    at Rr (markdown.js:110:14)
    at Er (markdown.js:135:23)
    at Object.run (markdown.js:204:3)
    at base-runner.js:71:24

**Comment by marcoscaceres** [comment]
Fixed by the marked upgrade to v16+ (commit 7229741d) and subsequent updates. The `parseInfoString` method now receives a default empty string from the marked token API, preventing the `TypeError` on `undefined.search()`.
